---
name: Chocolatey
on: push
jobs:
  choco-push:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push kerio-control-vpn-client.9.3.4367.nupkg -k="${{ secrets.APIKEY }}" --trace -s https://chocolatey.org/
